# Generated by Django 5.2 on 2025-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.jpg", upload_to="images/"
            ),
        ),
    ]
