# Generated by Django 5.2 on 2025-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="images/"
            ),
        ),
    ]
