# Generated by Django 5.1.4 on 2025-01-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_avatar_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
